---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec
#   format: doc

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[phylogeny::default]
    attributes:
